<?php

declare(strict_types=1);

namespace Prox\ProxGallery\Modules\DevelopmentSeed\Services;

use Prox\ProxGallery\Contracts\ServiceInterface;
use Prox\ProxGallery\Modules\Frontend\Services\FrontendGalleryService;
use Prox\ProxGallery\Modules\Frontend\Services\FrontendTrackingService;
use Prox\ProxGallery\Modules\Gallery\Services\GalleryService;
use Prox\ProxGallery\Modules\MediaLibrary\Models\UploadedImageQueueModel;
use Prox\ProxGallery\Modules\MediaLibrary\Services\MediaCategoryService;
use Prox\ProxGallery\Modules\MediaLibrary\Services\TrackUploadedImageService;

/**
 * Generates development seed data for media, galleries, and categories.
 */
final class DevelopmentSeedService implements ServiceInterface
{
    private const ONE_PIXEL_PNG_BASE64 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO7ZlYQAAAAASUVORK5CYII=';
    private const DEMO_TRACKING_DAYS = 365;

    /**
     * @var list<string>
     */
    private const CATEGORY_POOL = [
        'Nature',
        'Urban',
        'Portrait',
        'Travel',
        'Macro',
        'Architecture',
        'Landscape',
        'Street',
        'Black and White',
        'Editorial',
        'Night',
        'Food',
        'Product',
        'Documentary',
        'Fashion',
        'Minimal',
        'Adventure',
        'Coastal',
        'Mountains',
        'Wildlife',
    ];

    /**
     * @var list<string>
     */
    private const TITLE_PREFIXES = [
        'Golden',
        'Silent',
        'Wild',
        'Calm',
        'Northern',
        'Crimson',
        'Azure',
        'Echo',
        'Lunar',
        'Solar',
    ];

    /**
     * @var list<string>
     */
    private const TITLE_SUFFIXES = [
        'Horizon',
        'Frame',
        'Moment',
        'Story',
        'Capture',
        'Scene',
        'Vista',
        'Archive',
        'Memoir',
        'Signal',
    ];

    public function __construct(
        private GalleryService $galleryService,
        private FrontendGalleryService $frontendGalleryService,
        private FrontendTrackingService $trackingService,
        private MediaCategoryService $mediaCategoryService,
        private TrackUploadedImageService $trackService,
        private UploadedImageQueueModel $queue
    ) {
    }

    public function id(): string
    {
        return 'development.seed.service';
    }

    public function boot(): void
    {
        /**
         * Fires after development seed services are booted.
         */
        \do_action('prox_gallery/module/development_seed/service/booted', $this);
    }

    /**
     * @return array{
     *     requested_images:int,
     *     created_images:int,
     *     failed_images:int,
     *     requested_galleries:int,
     *     created_galleries:int,
     *     tracked_images:int,
     *     gallery_assignments:int,
     *     category_assignments:int,
     *     galleries:list<array{id:int, name:string, template:string}>
     * }
     */
    public function importRandomData(
        int $imageCount = 100,
        int $galleryCount = 6,
        int $maxCategoriesPerImage = 3,
        int $maxGalleriesPerImage = 3,
        bool $clearExisting = false
    ): array {
        $sanitizedImageCount = max(1, $imageCount);
        $sanitizedGalleryCount = max(1, $galleryCount);
        $sanitizedMaxCategories = max(0, $maxCategoriesPerImage);
        $sanitizedMaxGalleries = max(1, $maxGalleriesPerImage);

        if ($clearExisting) {
            $this->galleryService->clearAll();
            $this->queue->replaceAll([]);
        }

        $galleryRows = [];
        $galleryIds = [];
        $galleryTemplatePool = $this->availableTemplateSlugs();

        for ($index = 1; $index <= $sanitizedGalleryCount; $index++) {
            $template = $this->pickRandomString($galleryTemplatePool, 'basic-grid');
            $gallery = $this->galleryService->create(
                sprintf('Seed Gallery %d', $index),
                sprintf('Generated by prox seed import-random at %s', \gmdate('c')),
                $template
            );

            $galleryIds[] = (int) $gallery['id'];
            $galleryRows[] = [
                'id' => (int) $gallery['id'],
                'name' => (string) $gallery['name'],
                'template' => (string) $gallery['template'],
            ];
        }

        $createdImages = 0;
        $failedImages = 0;
        $trackedImages = 0;
        $galleryAssignments = 0;
        $categoryAssignments = 0;

        for ($index = 1; $index <= $sanitizedImageCount; $index++) {
            $attachmentId = $this->createSeedAttachment($index);

            if ($attachmentId <= 0) {
                $failedImages++;
                continue;
            }

            $createdImages++;

            if ($this->trackService->track($attachmentId)) {
                $trackedImages++;
            }

            $galleriesForImage = $this->pickRandomIntIds(
                $galleryIds,
                random_int(1, min($sanitizedMaxGalleries, count($galleryIds)))
            );
            $this->galleryService->setImageGalleries($attachmentId, $galleriesForImage);
            $galleryAssignments += count($galleriesForImage);

            if ($sanitizedMaxCategories > 0) {
                $categories = $this->pickRandomStrings(
                    self::CATEGORY_POOL,
                    random_int(0, $sanitizedMaxCategories)
                );

                if ($categories !== []) {
                    $this->mediaCategoryService->assignToAttachment($attachmentId, $categories);
                    $categoryAssignments += count($categories);
                }
            }
        }

        return [
            'requested_images' => $sanitizedImageCount,
            'created_images' => $createdImages,
            'failed_images' => $failedImages,
            'requested_galleries' => $sanitizedGalleryCount,
            'created_galleries' => count($galleryRows),
            'tracked_images' => $trackedImages,
            'gallery_assignments' => $galleryAssignments,
            'category_assignments' => $categoryAssignments,
            'galleries' => $galleryRows,
        ];
    }

    /**
     * @return array{
     *     traffic:string,
     *     requested_images:int,
     *     created_images:int,
     *     failed_images:int,
     *     requested_galleries:int,
     *     created_galleries:int,
     *     tracked_images:int,
     *     gallery_assignments:int,
     *     category_assignments:int,
     *     annual_gallery_views:int,
     *     annual_image_views:int,
     *     galleries:list<array{id:int, name:string, template:string}>
     * }
     */
    public function seedDashboardDemo(string $trafficProfile = 'medium', bool $clearExisting = false): array
    {
        $profile = $this->profileConfig($trafficProfile);
        $seed = $this->importRandomData(
            $profile['images'],
            $profile['galleries'],
            $profile['max_categories'],
            $profile['max_galleries'],
            $clearExisting
        );

        $galleryRows = $this->galleryService->list();
        $trackedImages = $this->queue->all();
        $stats = [
            'galleries' => [],
            'images' => [],
            'daily' => [
                'gallery_views' => [],
                'image_views' => [],
                'lightbox_opens' => [],
                'info_panel_opens' => [],
            ],
            'sources' => [],
            'devices' => [],
            'updated_at' => \gmdate('c'),
        ];

        $galleryPopularity = [];
        foreach ($galleryRows as $gallery) {
            $galleryId = (int) ($gallery['id'] ?? 0);

            if ($galleryId <= 0) {
                continue;
            }

            $galleryPopularity[$galleryId] = random_int(70, 140) / 100;
            $stats['galleries'][(string) $galleryId] = [
                'total' => 0,
                'countries' => [],
                'images' => [],
                'daily' => [],
                'lightbox_opens' => 0,
                'lightbox_daily' => [],
            ];

            $imageIds = isset($gallery['image_ids']) && is_array($gallery['image_ids']) ? $gallery['image_ids'] : [];
        }

        foreach ($trackedImages as $image) {
            $stats['images'][(string) $image->id] = [
                'total' => 0,
                'countries' => [],
                'daily' => [],
                'lightbox_opens' => 0,
                'lightbox_daily' => [],
                'info_opens' => 0,
                'info_daily' => [],
            ];
        }

        $countryWeights = $profile['countries'];
        $sourceWeights = $profile['sources'];
        $deviceWeights = $profile['devices'];
        $annualGalleryViews = 0;
        $annualImageViews = 0;

        for ($offset = self::DEMO_TRACKING_DAYS - 1; $offset >= 0; $offset--) {
            $dayKey = \gmdate('Y-m-d', strtotime('-' . $offset . ' days'));
            $seasonality = $this->seasonalityMultiplier($offset);
            $weekly = $this->weekdayMultiplier($dayKey);

            foreach ($galleryRows as $gallery) {
                $galleryId = (int) ($gallery['id'] ?? 0);

                if ($galleryId <= 0) {
                    continue;
                }

                $imageIds = isset($gallery['image_ids']) && is_array($gallery['image_ids']) ? array_values(array_filter(array_map('intval', $gallery['image_ids']))) : [];
                $galleryBase = $profile['gallery_day_base'] * ($galleryPopularity[$galleryId] ?? 1.0);
                $galleryCount = (int) round($galleryBase * $seasonality * $weekly * ($this->randomFloat(0.82, 1.22)));

                if ($galleryCount <= 0) {
                    continue;
                }

                $stats['galleries'][(string) $galleryId]['total'] += $galleryCount;
                $stats['galleries'][(string) $galleryId]['daily'][$dayKey] = $galleryCount;
                $stats['daily']['gallery_views'][$dayKey] = ($stats['daily']['gallery_views'][$dayKey] ?? 0) + $galleryCount;
                $annualGalleryViews += $galleryCount;

                foreach ($this->distributeCountByCountry($galleryCount, $sourceWeights) as $source => $count) {
                    $stats['sources'][$source] = ($stats['sources'][$source] ?? 0) + $count;
                }

                foreach ($this->distributeCountByCountry($galleryCount, $deviceWeights) as $device => $count) {
                    $stats['devices'][$device] = ($stats['devices'][$device] ?? 0) + $count;
                }

                foreach ($this->distributeCountByCountry($galleryCount, $countryWeights) as $country => $count) {
                    $stats['galleries'][(string) $galleryId]['countries'][$country] = ($stats['galleries'][(string) $galleryId]['countries'][$country] ?? 0) + $count;
                }

                if ($imageIds === []) {
                    continue;
                }

                $viewsPerVisit = $profile['image_multiplier_min'] + $this->randomFloat(0, $profile['image_multiplier_max'] - $profile['image_multiplier_min']);
                $imageViewCount = (int) round($galleryCount * $viewsPerVisit);
                $lightboxOpenCount = (int) round($galleryCount * $this->randomFloat($profile['lightbox_rate_min'], $profile['lightbox_rate_max']));
                $infoOpenCount = (int) round($lightboxOpenCount * $this->randomFloat($profile['info_rate_min'], $profile['info_rate_max']));

                if ($imageViewCount <= 0) {
                    continue;
                }

                $weights = [];

                foreach ($imageIds as $imageId) {
                    $weights[$imageId] = random_int(1, 100);

                    if (
                        ! isset($stats['galleries'][(string) $galleryId]['images'][(string) $imageId]) ||
                        ! is_array($stats['galleries'][(string) $galleryId]['images'][(string) $imageId])
                    ) {
                        $stats['galleries'][(string) $galleryId]['images'][(string) $imageId] = [
                            'total' => 0,
                            'countries' => [],
                            'daily' => [],
                            'lightbox_opens' => 0,
                            'lightbox_daily' => [],
                            'info_opens' => 0,
                            'info_daily' => [],
                        ];
                    }
                }

                foreach ($this->distributeWeightedCounts($imageViewCount, $weights) as $imageId => $count) {
                    if ($count <= 0) {
                        continue;
                    }

                    $stats['images'][(string) $imageId]['total'] += $count;
                    $stats['images'][(string) $imageId]['daily'][$dayKey] = ($stats['images'][(string) $imageId]['daily'][$dayKey] ?? 0) + $count;
                    $stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['total'] += $count;
                    $stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['daily'][$dayKey] = ($stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['daily'][$dayKey] ?? 0) + $count;
                    $stats['daily']['image_views'][$dayKey] = ($stats['daily']['image_views'][$dayKey] ?? 0) + $count;
                    $annualImageViews += $count;

                    foreach ($this->distributeCountByCountry($count, $countryWeights) as $country => $countryCount) {
                        $stats['images'][(string) $imageId]['countries'][$country] = ($stats['images'][(string) $imageId]['countries'][$country] ?? 0) + $countryCount;
                        $stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['countries'][$country] =
                            ($stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['countries'][$country] ?? 0) + $countryCount;
                    }
                }

                if ($lightboxOpenCount > 0) {
                    $stats['galleries'][(string) $galleryId]['lightbox_opens'] += $lightboxOpenCount;
                    $stats['galleries'][(string) $galleryId]['lightbox_daily'][$dayKey] =
                        ($stats['galleries'][(string) $galleryId]['lightbox_daily'][$dayKey] ?? 0) + $lightboxOpenCount;
                    $stats['daily']['lightbox_opens'][$dayKey] = ($stats['daily']['lightbox_opens'][$dayKey] ?? 0) + $lightboxOpenCount;

                    foreach ($this->distributeWeightedCounts($lightboxOpenCount, $weights) as $imageId => $count) {
                        if ($count <= 0) {
                            continue;
                        }

                        $stats['images'][(string) $imageId]['lightbox_opens'] += $count;
                        $stats['images'][(string) $imageId]['lightbox_daily'][$dayKey] =
                            ($stats['images'][(string) $imageId]['lightbox_daily'][$dayKey] ?? 0) + $count;
                        $stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['lightbox_opens'] += $count;
                        $stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['lightbox_daily'][$dayKey] =
                            ($stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['lightbox_daily'][$dayKey] ?? 0) + $count;
                    }
                }

                if ($infoOpenCount > 0) {
                    $stats['daily']['info_panel_opens'][$dayKey] = ($stats['daily']['info_panel_opens'][$dayKey] ?? 0) + $infoOpenCount;

                    foreach ($this->distributeWeightedCounts($infoOpenCount, $weights) as $imageId => $count) {
                        if ($count <= 0) {
                            continue;
                        }

                        $stats['images'][(string) $imageId]['info_opens'] += $count;
                        $stats['images'][(string) $imageId]['info_daily'][$dayKey] =
                            ($stats['images'][(string) $imageId]['info_daily'][$dayKey] ?? 0) + $count;
                        $stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['info_opens'] += $count;
                        $stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['info_daily'][$dayKey] =
                            ($stats['galleries'][(string) $galleryId]['images'][(string) $imageId]['info_daily'][$dayKey] ?? 0) + $count;
                    }
                }
            }
        }

        $stats['updated_at'] = \gmdate('c');
        $this->trackingService->replaceStats($stats);

        return [
            ...$seed,
            'traffic' => $profile['name'],
            'annual_gallery_views' => $annualGalleryViews,
            'annual_image_views' => $annualImageViews,
        ];
    }

    private function createSeedAttachment(int $index): int
    {
        $image = $this->buildSeedImagePayload($index);

        if ($image === null) {
            return 0;
        }

        $upload = \wp_upload_bits(
            $image['filename'],
            null,
            $image['binary']
        );

        $uploadError = isset($upload['error']) ? (string) $upload['error'] : '';

        if ($uploadError !== '' || ! isset($upload['file']) || ! is_string($upload['file'])) {
            return 0;
        }

        $title = sprintf('%s %s %d', $this->randomTitlePrefix(), $this->randomTitleSuffix(), $index);

        $attachmentId = \wp_insert_attachment(
            [
                'post_title' => $title,
                'post_mime_type' => $image['mime_type'],
                'post_status' => 'inherit',
                'post_type' => 'attachment',
            ],
            $upload['file']
        );

        if (! is_int($attachmentId) || $attachmentId <= 0) {
            return 0;
        }

        if (! function_exists('wp_generate_attachment_metadata')) {
            $imageSupportPath = \defined('ABSPATH') ? \ABSPATH . 'wp-admin/includes/image.php' : '';

            if ($imageSupportPath !== '' && is_file($imageSupportPath)) {
                require_once $imageSupportPath;
            }
        }

        if (function_exists('wp_generate_attachment_metadata')) {
            $metadata = \wp_generate_attachment_metadata($attachmentId, $upload['file']);

            if (is_array($metadata) && function_exists('wp_update_attachment_metadata')) {
                \wp_update_attachment_metadata($attachmentId, $metadata);
            }
        }

        return $attachmentId;
    }

    /**
     * @return array{filename:string, mime_type:string, binary:string}|null
     */
    private function buildSeedImagePayload(int $index): ?array
    {
        if (function_exists('imagecreatetruecolor') && function_exists('imagejpeg')) {
            $width = random_int(900, 1800);
            $height = random_int(700, 1300);
            $resource = imagecreatetruecolor($width, $height);

            if ($resource === false) {
                return null;
            }

            $topR = random_int(10, 180);
            $topG = random_int(10, 180);
            $topB = random_int(10, 180);
            $bottomR = random_int(60, 240);
            $bottomG = random_int(60, 240);
            $bottomB = random_int(60, 240);

            for ($y = 0; $y < $height; $y++) {
                $mix = $height > 1 ? $y / ($height - 1) : 0;
                $r = (int) round($topR + (($bottomR - $topR) * $mix));
                $g = (int) round($topG + (($bottomG - $topG) * $mix));
                $b = (int) round($topB + (($bottomB - $topB) * $mix));
                $lineColor = imagecolorallocate($resource, $r, $g, $b);

                if ($lineColor === false) {
                    continue;
                }

                imageline($resource, 0, $y, $width, $y, $lineColor);
            }

            $shapeCount = random_int(8, 18);

            for ($i = 0; $i < $shapeCount; $i++) {
                $color = imagecolorallocatealpha(
                    $resource,
                    random_int(30, 255),
                    random_int(30, 255),
                    random_int(30, 255),
                    random_int(50, 95)
                );

                if ($color === false) {
                    continue;
                }

                imagefilledellipse(
                    $resource,
                    random_int(0, $width),
                    random_int(0, $height),
                    random_int((int) floor($width * 0.05), (int) floor($width * 0.45)),
                    random_int((int) floor($height * 0.05), (int) floor($height * 0.45)),
                    $color
                );
            }

            $overlay = imagecolorallocatealpha($resource, 255, 255, 255, 70);
            if ($overlay !== false) {
                imagestring($resource, 5, 14, 14, sprintf('PROX SEED %04d', $index), $overlay);
            }

            ob_start();
            imagejpeg($resource, null, 87);
            $binary = (string) ob_get_clean();
            imagedestroy($resource);

            if ($binary === '') {
                return null;
            }

            return [
                'filename' => sprintf('prox-seed-%s-%04d.jpg', \gmdate('YmdHis'), $index),
                'mime_type' => 'image/jpeg',
                'binary' => $binary,
            ];
        }

        $fallback = (string) \base64_decode(self::ONE_PIXEL_PNG_BASE64);

        if ($fallback === '') {
            return null;
        }

        return [
            'filename' => sprintf('prox-seed-%s-%04d.png', \gmdate('YmdHis'), $index),
            'mime_type' => 'image/png',
            'binary' => $fallback,
        ];
    }

    private function randomTitlePrefix(): string
    {
        return $this->pickRandomString(self::TITLE_PREFIXES, 'Seed');
    }

    private function randomTitleSuffix(): string
    {
        return $this->pickRandomString(self::TITLE_SUFFIXES, 'Image');
    }

    /**
     * @return array{
     *   name:string,
     *   images:int,
     *   galleries:int,
     *   max_categories:int,
     *   max_galleries:int,
     *   gallery_day_base:float,
     *   image_multiplier_min:float,
     *   image_multiplier_max:float,
     *   countries:array<string,int>
     * }
     */
    private function profileConfig(string $trafficProfile): array
    {
        $normalized = strtolower(trim($trafficProfile));

        return match ($normalized) {
            'low' => [
                'name' => 'low',
                'images' => 48,
                'galleries' => 6,
                'max_categories' => 2,
                'max_galleries' => 2,
                'gallery_day_base' => 3.4,
                'image_multiplier_min' => 1.4,
                'image_multiplier_max' => 2.2,
                'lightbox_rate_min' => 0.18,
                'lightbox_rate_max' => 0.34,
                'info_rate_min' => 0.18,
                'info_rate_max' => 0.42,
                'countries' => ['NL' => 40, 'DE' => 18, 'BE' => 14, 'FR' => 10, 'GB' => 8, 'US' => 10],
                'sources' => ['direct' => 30, 'internal' => 22, 'instagram' => 18, 'google' => 12, 'facebook' => 8, 'pinterest' => 10],
                'devices' => ['desktop' => 56, 'mobile' => 32, 'tablet' => 12],
            ],
            'high' => [
                'name' => 'high',
                'images' => 260,
                'galleries' => 18,
                'max_categories' => 4,
                'max_galleries' => 5,
                'gallery_day_base' => 24.0,
                'image_multiplier_min' => 2.8,
                'image_multiplier_max' => 4.6,
                'lightbox_rate_min' => 0.28,
                'lightbox_rate_max' => 0.46,
                'info_rate_min' => 0.22,
                'info_rate_max' => 0.48,
                'countries' => ['NL' => 18, 'DE' => 12, 'BE' => 9, 'FR' => 7, 'GB' => 10, 'US' => 18, 'IT' => 6, 'ES' => 6, 'AU' => 5, 'CA' => 9],
                'sources' => ['direct' => 16, 'internal' => 18, 'instagram' => 22, 'google' => 16, 'facebook' => 8, 'pinterest' => 10, 'linkedin' => 10],
                'devices' => ['desktop' => 41, 'mobile' => 46, 'tablet' => 13],
            ],
            default => [
                'name' => 'medium',
                'images' => 120,
                'galleries' => 10,
                'max_categories' => 3,
                'max_galleries' => 3,
                'gallery_day_base' => 10.0,
                'image_multiplier_min' => 2.0,
                'image_multiplier_max' => 3.2,
                'lightbox_rate_min' => 0.22,
                'lightbox_rate_max' => 0.4,
                'info_rate_min' => 0.2,
                'info_rate_max' => 0.45,
                'countries' => ['NL' => 28, 'DE' => 14, 'BE' => 10, 'FR' => 8, 'GB' => 9, 'US' => 16, 'IT' => 5, 'CA' => 6, 'ES' => 4],
                'sources' => ['direct' => 20, 'internal' => 20, 'instagram' => 20, 'google' => 14, 'facebook' => 8, 'pinterest' => 8, 'linkedin' => 10],
                'devices' => ['desktop' => 48, 'mobile' => 40, 'tablet' => 12],
            ],
        };
    }

    private function seasonalityMultiplier(int $daysAgo): float
    {
        $position = self::DEMO_TRACKING_DAYS - $daysAgo;
        $yearWave = 1 + (sin(($position / 365) * 2 * M_PI) * 0.22);
        $quarterWave = 1 + (sin(($position / 90) * 2 * M_PI) * 0.12);

        return max(0.45, $yearWave + $quarterWave);
    }

    private function weekdayMultiplier(string $dayKey): float
    {
        $weekday = (int) \gmdate('N', strtotime($dayKey . ' 00:00:00 UTC'));

        return match ($weekday) {
            6 => 1.18,
            7 => 1.12,
            5 => 1.08,
            default => 0.94,
        };
    }

    private function randomFloat(float $min, float $max): float
    {
        $random = random_int(0, 10000) / 10000;

        return $min + (($max - $min) * $random);
    }

    /**
     * @param array<string, int> $weights
     *
     * @return array<string, int>
     */
    private function distributeCountByCountry(int $count, array $weights): array
    {
        return $this->distributeWeightedCounts($count, $weights);
    }

    /**
     * @param array<int|string, int> $weights
     *
     * @return array<int|string, int>
     */
    private function distributeWeightedCounts(int $count, array $weights): array
    {
        if ($count <= 0 || $weights === []) {
            return [];
        }

        $totalWeight = array_sum($weights);

        if ($totalWeight <= 0) {
            return [];
        }

        $assigned = [];
        $remainders = [];
        $allocated = 0;

        foreach ($weights as $key => $weight) {
            $share = ($count * max(0, (int) $weight)) / $totalWeight;
            $base = (int) floor($share);
            $assigned[$key] = $base;
            $allocated += $base;
            $remainders[$key] = $share - $base;
        }

        $remaining = $count - $allocated;

        if ($remaining > 0) {
            arsort($remainders);

            foreach (array_keys($remainders) as $key) {
                if ($remaining <= 0) {
                    break;
                }

                $assigned[$key] = ($assigned[$key] ?? 0) + 1;
                $remaining--;
            }
        }

        return $assigned;
    }

    /**
     * @return list<string>
     */
    private function availableTemplateSlugs(): array
    {
        $rows = $this->frontendGalleryService->templateCatalog();
        $slugs = [];

        foreach ($rows as $row) {
            if (! is_array($row)) {
                continue;
            }

            $slug = isset($row['slug']) ? (string) $row['slug'] : '';
            $available = isset($row['available']) && (bool) $row['available'];

            if ($slug === '' || ! $available) {
                continue;
            }

            $slugs[] = $slug;
        }

        if ($slugs === []) {
            return ['basic-grid'];
        }

        return array_values(array_unique($slugs));
    }

    /**
     * @param list<int> $source
     *
     * @return list<int>
     */
    private function pickRandomIntIds(array $source, int $count): array
    {
        if ($source === []) {
            return [];
        }

        $copy = array_values(array_unique($source));
        shuffle($copy);

        return array_slice($copy, 0, max(0, min($count, count($copy))));
    }

    /**
     * @param list<string> $source
     *
     * @return list<string>
     */
    private function pickRandomStrings(array $source, int $count): array
    {
        if ($source === []) {
            return [];
        }

        $copy = array_values(array_unique($source));
        shuffle($copy);

        return array_slice($copy, 0, max(0, min($count, count($copy))));
    }

    /**
     * @param list<string> $source
     */
    private function pickRandomString(array $source, string $fallback): string
    {
        if ($source === []) {
            return $fallback;
        }

        $index = random_int(0, count($source) - 1);
        $value = isset($source[$index]) ? (string) $source[$index] : '';

        return $value !== '' ? $value : $fallback;
    }
}
